### ISSUE TITLE
Wrong "delete-unused-entries-js-plugin" with plugin ExtendedAPIPlugin

### ISSUE THREAD

**Issue by onEXHovia** [symfony/webpack-encore#197]
Hello guys, if used plugin ExtendedAPIPlugin for access __webpack_hash__, then the exception occurs during the assembly "Problem deleting JS entry for style: 0 files were deleted"

Configuration:
```
let Encore = require('@symfony/webpack-encore');
let CopyWebpackPlugin = require('copy-webpack-plugin');
let ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
let ExtendedAPIPlugin = require('webpack/lib/ExtendedAPIPlugin');
let SvgStorePlugin = require('webpack-svgstore-plugin');

let rupture = require('rupture');
let svgStoreOptions = {
  name: 'icons.svg',
  prefix: 'icon-',
  svgoOptions: {
    plugins: [
      { removeTitle: true }
    ]
  }
};

Encore
  .setOutputPath('web/dist')
  .setPublicPath('/dist')
  .cleanupOutputBeforeBuild()
  .enableSourceMaps(!Encore.isProduction())
  .autoProvidejQuery()
  .autoProvideVariables({
    'Sortable': require.resolve('sortablejs'),
    '_': 'underscore'
  })
  .enableVersioning()
  .enableTypeScriptLoader()
  .enableStylusLoader((options) => {
    options.set = { 'include css': true };
    options.use = [rupture()];
  })
  .configureManifestPlugin((options) => {
    options.fileName = '../manifest_webpack.json'
  })
  .addPlugin(new ExtendedAPIPlugin())
  .addPlugin(new CopyWebpackPlugin([{ from: 'assets/images', to: 'images' }]))
  .addPlugin(new ContextReplacementPlugin(/moment[\/\\]locale$/, /ru/))
  .addPlugin(new SvgStorePlugin('assets/icons/*.svg', '/', svgStoreOptions))
  .addEntry('index', './assets/common')
  .addEntry('critical', './assets/critical')
  .addStyleEntry('style', './assets/common.styl')
;  
```

Exception:
```
/var/www/project/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:39
                    throw new Error(`Problem deleting JS entry for ${chunk.name}: ${fileDeleteCount} files were deleted`);
                    ^

Error: Problem deleting JS entry for style: 0 files were deleted
    at compilation.chunks.forEach (/var/www/project/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:39:27)
    at Array.forEach (native)
    at Compiler.compiler.plugin (/var/www/project/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:19:28)
    at Compiler.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:206:13)
    at Compiler.emitAssets (/var/www/project/node_modules/webpack/lib/Compiler.js:358:8)
    at onCompiled (/var/www/project/node_modules/webpack/lib/Compiler.js:244:9)
    at applyPluginsAsync.err (/var/www/project/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/var/www/project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/var/www/project/node_modules/ts-loader/dist/after-compile.js:25:9)
    at next (/var/www/project/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/var/www/project/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/var/www/project/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/var/www/project/node_modules/webpack/lib/Compilation.js:680:19)
    at Compilation.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/var/www/project/node_modules/webpack/lib/Compilation.js:671:11)
    at Compilation.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/var/www/project/node_modules/webpack/lib/Compilation.js:666:10)
    at next (/var/www/project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/var/www/project/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/var/www/project/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/var/www/project/node_modules/webpack/lib/Compilation.js:662:9)
    at next (/var/www/project/node_modules/tapable/lib/Tapable.js:202:11)
    at /var/www/project/node_modules/extract-text-webpack-plugin/dist/index.js:244:13
    at /var/www/project/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/var/www/project/node_modules/async/dist/async.js:1050:13)
    at /var/www/project/node_modules/async/dist/async.js:958:16
    at /var/www/project/node_modules/extract-text-webpack-plugin/dist/index.js:227:15
    at /var/www/project/node_modules/async/dist/async.js:473:16
```

**Comment by Lyrkan** [comment]
Hi @onEXHovia,

Thank you for opening this issue, I can reproduce it on my side with this minimal config:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');
const ExtendedAPIPlugin = require('webpack/lib/ExtendedAPIPlugin');

Encore
  .setOutputPath('build/')
  .setPublicPath('/')
  .cleanupOutputBeforeBuild()
  .enableVersioning()
  .addStyleEntry('styles', './src/index.css')
  .addPlugin(new ExtendedAPIPlugin())
;

module.exports = Encore.getWebpackConfig();
```

It only seems to happen if versioning is enabled.

**Comment by Lyrkan** [comment]
Well, it looks like it is related to this `ExtendedAPIPlugin` issue: webpack/webpack#5337.

When you enable versioning the default filename used for JS entry points is `[name].[chunkhash].js`, so if you remove the line that throws the "0 files were deleted" error, it keeps failing for the following reason:

```
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```

I'm not sure what you could do to make it work... I guess you could change the naming strategy to use `[hash]` instead of `[chunkhash]` but you'll have to keep in mind that it is a [build specific hash](https://webpack.js.org/guides/caching/#output-filenames):

```js
Encore.configureFilenames({ js: '[name].[hash].js' });
```

**Comment by stof** [comment]
using the hash instead of the chunkhash is very bad for caching (as it invalidates the whole cache all the time)

**Comment by Lyrkan** [comment]
It definitely is, but the only other solutions I see would be:

* to disable versioning (at least for JS files using `.configureFilenames({ js: '[name].js' })`)
* to get rid of that pluging (maybe some community ones provide the same feature?)

**Comment by weaverryan** [comment]
Hmm, yea... I think we can't do anything, as it *does* seem like this is a bug in Webpack itself (webpack/webpack#5337). The user will need to workaround it by one of the two things you mentioned. They could also do `.configureFilenames({ js: '[name].[hash].js' })`, but that's up to them (since we don't want to do that anywhere).

Unless I'm missing something, I think we should close this issue - it's a bug in Webpack!

**Comment by onEXHovia** [comment]
Thanks for the answers, close the issue.
