### ISSUE TITLE
Cannot find RequestShortener

### ISSUE THREAD

**Issue by garak** [symfony/webpack-encore#222]
npm 5.5.1, nodejs v8.9.1, encore ^0.17
When I try `./node_modules/.bin/encore production` I get the following error:
```
Running webpack ...

module.js:538
    throw err;
    ^

Error: Cannot find module 'webpack/lib/RequestShortener'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/garak/garak3/node_modules/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:4:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by Lyrkan** [comment]
Hi @garak,

I can't reproduce your issue with a minimal install could you give us the output of `npm ls | grep webpack`?

**index.js:**

```js
console.log('Hi!');
```

**package.json:**

```json
{
  "name": "encore-issue-222",
  "version": "1.0.0"
}
```

**webpack.config.js:**

```js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('build/')
    .setPublicPath('/')
    .cleanupOutputBeforeBuild()
    .addEntry('main', './index.js')
;

module.exports = Encore.getWebpackConfig();
```

**Console output:**

```
$ ls
index.js  package.json  webpack.config.js

$ npm install --save-dev @symfony/webpack-encore@^0.17
(...)
+ @symfony/webpack-encore@0.17.0
added 854 packages in 19.469s

$ ./node_modules/.bin/encore production                                                                                                                             
Running webpack ...

 DONE  Compiled successfully in 298ms                                                                                                                                                                                          19:27:49

 I  2 files written to build

$ node ./build/main.js
Hi!
```

**Comment by garak** [comment]
Thanks for support and for fast reply.
I tried the small code and it worked. So, I tried to delete package-lock.json from my main project and re-install everything, and now the problem is gone.
