### ISSUE TITLE
Problem with example giving in documentation

### ISSUE THREAD

**Issue by roflmanya** [symfony/webpack-encore#31]
I tried to follow the instructions on [Symfony blog](http://symfony.com/doc/current/frontend/encore/simple-example.html), but when i tried to build:
```
C:\projects\webpack-encore>encore dev
Running webpack ...

C:\projects\webpack-encore\node_modules\@symfony\webpack-encore\index.js:11
    throw new Error('Are you trying to require index.js directly?');
    ^

Error: Are you trying to require index.js directly?
    at Object.<anonymous> (C:\projects\webpack-encore\node_modules\@symfony\webpack-encore\index.js:11:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\projects\webpack-encore\webpack.config.js:2:14)
    at Module._compile (module.js:570:32)
```
what am I doing wrong?

**Comment by weaverryan** [comment]
Hey @roflmanya!

It looks like you're using a globally installed encore executable, instead of installing it into your project. Is that true? It's quite possible the executable doesn't work globally... and in not sure if we should support that anyways. But, we should have a better error :).

**Comment by roflmanya** [comment]
@weaverryan thanks =)
