### ISSUE TITLE
Error on run encore dev

### ISSUE THREAD

**Issue by m3ldro** [symfony/webpack-encore#325]
Hallo, i'm on  Windows 10 with git-bash terminal and yarn, nodejs and npm correctly added in $PATH

If I try to run encore using

`node ./node_modules/.bin/encore dev`

I've got this error:

```
C:\xampp7\htdocs\symfony\testproject\node_modules\.bin\encore:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

So, what's i'm wrong?
Thanks in advance

**Comment by Lyrkan** [comment]
Hi @m3ldro,

Which version of node/npm are you using?

Could you also try the following commands instead?

```
$ yarn run encore dev
$ ./node_modules/.bin/encore dev
$ ./node_modules/@symfony/webpack-encore/bin/encore.js dev
```

**Comment by Lyrkan** [comment]
Great, I suspect some weird handling of the symbolic links located in `./node_modules/.bin` on Windows... but I don't think we can do something to fix that in Encore :(
