### ISSUE TITLE
extract-text-plugin still not working 

### ISSUE THREAD

**Issue by Shadowzyx** [symfony/webpack-encore#332]
Hi guys, I had this issue with extract-text-plugin after upgrading to weback 4 :
```
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/var/www/html/node_modules/webpack/lib/Chunk.js:741:9)
    at /var/www/html/node_modules/@symfony/webpack-encore/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /var/www/html/node_modules/@symfony/webpack-encore/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/www/html/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/var/www/html/node_modules/webpack/lib/Compilation.js:904:27)
    at hooks.make.callAsync.err (/var/www/html/node_modules/webpack/lib/Compiler.js:494:17)
    at _err0 (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/var/www/html/node_modules/webpack/lib/Compilation.js:770:12)
    at processModuleDependencies.err (/var/www/html/node_modules/webpack/lib/Compilation.js:709:9)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

As seen everywhere, I tried to fix this by running `npm i -D extract-text-webpack-plugin@next`, but this is not working. I think this is because the error is happening inside webpack encore's own node_modules... 

Any ida ?

**Comment by stof** [comment]
Webpack Encore requires webpack 3 currently. Support for webpack 4 is a WIP in #324

**Comment by aphex008** [comment]
Same here. Installed webpack 4 and tried to run 
```
yarn encore dev. 
```
Removing webpack 4 dependency and reinstalling node modules helped.
