### ISSUE TITLE
Cannot find module './lib/compilers'

### ISSUE THREAD

**Issue by Tahakun** [symfony/webpack-encore#381]
package.json

```
{
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.3.1",
    "@symfony/webpack-encore": "^0.20.1",
    "bootstrap": "^4.1.3",
    "node-sass": "^4.9.3",
    "popper.js": "^1.14.4",
    "sass-loader": "^7.1.0",
    "webpack-cli": "^3.1.0"
  },
  "dependencies": {
    "jquery": "^3.3.1",
    "webpack": "3.12"
  }
}

```

webpack.config.js

```
var Encore = require('@symfony/webpack-encore');

Encore
    // directory where compiled assets will be stored
    .setOutputPath('web/build/')
    // public path used by the web server to access the output path
    .setPublicPath('/build')

    /*
     * ENTRY CONFIG
     *
     * Add 1 entry for each "page" of your app
     * (including one that's included on every page - e.g. "app")
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if you JavaScript imports CSS.
     */
    .createSharedEntry('app', './assets/js/app.js')
    .addStyleEntry('styles', './assets/scss/styles.scss')

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    //.addEntry('page1', './assets/js/page1.js')
    //.addEntry('page2', './assets/js/page2.js')

    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    // uncomment if you use TypeScript
    //.enableTypeScriptLoader()

    // uncomment if you use Sass/SCSS files
    .enableSassLoader()

    // uncomment if you're having problems with a jQuery plugin
    .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();
```

When i use the the command `yarn encore dev --watch` i get the error

```
Running webpack ...


Webpack is watching the files…

 DONE  Compiled successfully in 4745ms                                                                                                                                                                      11:34:23

 I  4 files written to web/build
module.js:545
    throw err;
    ^

Error: Cannot find module './lib/compilers'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/project/node_modules/anymatch/node_modules/micromatch/index.js:16:17)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/project/node_modules/anymatch/index.js:3:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/project/node_modules/chokidar/index.js:6:16)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/project/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (module.js:649:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn list webpack

```
warning package.json: No license field
warning No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ webpack@3.12.0
Done in 0.95s.
```

PS `yarn encore dev` works, the problem occur when I add the `--watch`

**Comment by royklutman** [comment]
I'm by no means an expert on this particular subject, but have you tried removing your `node_modules` folder and running `yarn install`? Also, just a friendly reminder, don't forget to rerun `yarn encore dev --watch` every time you make a change in `webpack.config.js`. Oh, and if you are using Webpack for no other reason then for Encore, you don't need to manually install `webpack` and `webpack-cli` because `@symfony/webpack-encore` includes it for you.

**Comment by Tahakun** [comment]
I tried removing the `node_modules` and rerun `yarn install`, I still get the same error

**Comment by Lyrkan** [comment]
@Tahakun Did you also remove `webpack` and `webpack-cli` for your dependencies?

As @royklutman said Encore already includes Webpack so you don't have to add it to your project manually (that can cause some issues since the two versions may not be the same).

**Comment by Tahakun** [comment]
Yes, I did, here is the new package.json,

```
{
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.3.1",
    "@symfony/webpack-encore": "^0.20.1",
    "bootstrap": "^4.1.3",
    "node-sass": "^4.9.3",
    "popper.js": "^1.14.4",
    "sass-loader": "^7.1.0",
    "semantic-ui-sass": "^2.3.1"
  },
  "dependencies": {
    "jquery": "^3.3.1"
  }
}
```

**Comment by royklutman** [comment]
I tried replicating but I don't seem to get the error message, have you also tried removing the `yarn.lock` and/or `package.lock` files and the `node_modules` folder and then running `yarn install`? Does the error also show when you comment the following line: `//.createSharedEntry('app', './assets/js/app.js')`?

**Comment by Tahakun** [comment]
Hi, it looks like the problem is not from webpack-encore, i tried to run standalone webpack and i have the same error
