### ISSUE TITLE
 throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by Jackson8Zhang** [symfony/webpack-encore#44]
```
z@kf:~/codes/php/website> ./node_modules/.bin/encore dev
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at find (/home/zlf/codes/php/website/node_modules/babel-loader/lib/resolve-rc.js:11:21)
    at module.exports (/home/zlf/codes/php/website/node_modules/@symfony/webpack-encore/lib/config/parse-runtime.js:64:47)
    at Object.<anonymous> (/home/zlf/codes/php/website/node_modules/@symfony/webpack-encore/bin/encore.js:18:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
z@kf:~/codes/php/website> node -v
v6.11.0

**Comment by Jackson8Zhang** [comment]
see #40

**Comment by subhashekkaluru** [comment]
![01](https://user-images.githubusercontent.com/20380015/38303225-0385ac58-3823-11e8-9feb-5233dba81917.JPG)
please solve this.
Thanks

**Comment by Lyrkan** [comment]
@subhashekkaluru It doesn't look like you are using Encore in your screenshot

**Comment by subhashekkaluru** [comment]
am new this can anyone solve this
