### ISSUE TITLE
@font-face cssSyntaxError unknown word in production

### ISSUE THREAD

**Issue by maisoui** [symfony/webpack-encore#496]
Hi,

Since a last update I have a problem with the command: _yarn run encore production_.
I received this error: **CssSyntaxError: Unknown word**
I found that the **@font-face** is causing the issue. What is the problem?
No problem in 'dev' mode and no problem since no problem until today (before yarn upgrade).

Best regards

**Comment by Kocal** [comment]
Maybe related to https://github.com/postcss/postcss/issues/1229 ?

**Comment by maisoui** [comment]
Hi,

I do not understand the problem and I have been looking for a solution for hours. For now, as a workaround, I generate for 'dev' in my production environment.

with command **yarn run encore dev**, no problem. To reproduce the issue, simply execute command **yarn run encore production**:

`Running webpack ...

CssSyntaxError: /var/www-myproject/web/app.f601c855.css:42:5: Unknown word
    at Input.error (/var/www-myproject/web/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/var/www-myproject/web/node_modules/postcss/lib/parser.js:563:22)
    at Parser.decl (/var/www-myproject/web/node_modules/postcss/lib/parser.js:235:16)
    at Parser.other (/var/www-myproject/web/node_modules/postcss/lib/parser.js:133:18)
    at Parser.parse (/var/www-myproject/web/node_modules/postcss/lib/parser.js:77:16)
    at parse (/var/www-myproject/web/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/var/www-myproject/web/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/var/www-myproject/web/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/var/www-myproject/web/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/var/www-myproject/web/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/var/www-myproject/web/node_modules/optimize-css-assets-webpack-plugin/src/index.js:65:21)
    at Object.processor (/var/www-myproject/web/node_modules/optimize-css-assets-webpack-plugin/src/index.js:11:18)
    at each (/var/www-myproject/web/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/var/www-myproject/web/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/var/www-myproject/web/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/var/www-myproject/web/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/var/www-myproject/web/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _err0 (eval at create (/var/www-myproject/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:13:17)
    at taskRunner.run (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/index.js:318:9)
    at step (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:83:9)
    at done (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:94:30)
    at boundWorkers (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:99:13)
    at TaskRunner.boundWorkers (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:68:11)
    at enqueue (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:14)
    at tasks.forEach (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:109:9)
    at Array.forEach (<anonymous>)
    at TaskRunner.run (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:11)
    at TerserPlugin.optimizeFn (/var/www-myproject/web/node_modules/terser-webpack-plugin/dist/index.js:224:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www-myproject/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www-myproject/web/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/var/www-myproject/web/node_modules/webpack/lib/Compilation.js:1311:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www-myproject/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www-myproject/web/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/var/www-myproject/web/node_modules/webpack/lib/Compilation.js:1307:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www-myproject/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www-myproject/web/node_modules/tapable/lib/Hook.js:154:20)`



By commenting the require of the css file, problem dissappear:
`require('css/icons/icomoon/styles.css');`

The content of the css file is:
`@font-face {
	font-family: 'icomoon';
	src:url('fonts/icomoon.eot?3p0rtw');
	src:url('fonts/icomoon.eot?#iefix3p0rtw') format('embedded-opentype'),
		url('fonts/icomoon.woff?3p0rtw') format('woff'),
		url('fonts/icomoon.ttf?3p0rtw') format('truetype'),
		url('fonts/icomoon.svg?3p0rtw#icomoon') format('svg');
	font-weight: normal;
	font-style: normal;
}

[class^="icon-"], [class*=" icon-"] {
    /* Use !important to prevent issues with browser extensions that change fonts */
	font-family: 'icomoon' !important;
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;
	min-width: 1em;
	display: inline-block;
	text-align: center;
	font-size: 16px;
	vertical-align: middle;
	position: relative;
	top: -1px;

	/* Better Font Rendering =========== */
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}

.icon-2x {
	font-size: 32px;
}
.icon-3x {
	font-size: 48px;
}

.icon-bordered {
	// padding: 5px;
	// border: 2px solid;
	// border-radius: 50%;
}`

I hope it can help you.
Best regards,
Jonathan

**Comment by Lyrkan** [comment]
@maisoui I edited your last comment to make it a bit easier to read (you need to use three backticks for multiline code blocks).

The problem comes from the last block of the `styles.css` file (you can see that it still fails after removing everything else).

Single-line comments (`//`) are not a valid CSS syntax, you need to use `/* ... */`.

**Comment by maisoui** [comment]
Ok thank you for your help and your resolution. It would then be necessary to improve the output of the verbose (because it showed me that he did not know the word **@fontface**).

Last question, why is the result (of yarn run encore...) different between _dev_ and _prod_? I generate in _prod_ only during deployments and having an issue at this step is very problematic.

Best regards

**Comment by Lyrkan** [comment]
I don't see any reference to `@fontface` in the output... only that the error occured in `/var/www-myproject/web/app.f601c855.css` at line 42 (which is probably not the line number from your original file since it has already been processed by the css-loader).

We can't really do anything to improve that message since it is generated by `postcss` and doesn't really contain any additional info... if we were to transform it we could only display that the postcss parser encountered a syntax error.

For your last question, well... if the output was the same between `dev` and `production` we wouldn't need both of them :)

When you call `yarn encore production` it does additional optimizations that take more time and are not needed during dev. For instance it minifies your JS/CSS or changes things in it to make it compatible with the browsers targeted by your build.

These extra step can use tools that are not used in a `dev` build at all, which is probably the case here.

In my opinion that's always a good idea to test things in `production` mode regularly (for instance before pushing or in your CI pipeline) because you can't be sure that there won't be an issue (which won't necessarily be a verbose crash like that one) caused by one of those optimizations.
