### ISSUE TITLE
addRule/addLoader method seem not working well

### ISSUE THREAD

**Issue by Jerome1337** [symfony/webpack-encore#507]
When I try to add a new rule to my webpack config with 

```javascript
const Encore = require('@symfony/webpack-encore');

Encore
  // ...
  .addRule({
    parser: {
      amd: false,
    },
  })
  // ...
```

The webpack compilation crash with the next error

```
$ encore dev
Running webpack ...

/code/node_modules/webpack-cli/bin/cli.js:235
				throw err;
				^

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/code/webpack.config.js:64:17)
    at Module._compile (/code/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (/code/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/code/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/code/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /code/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/code/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/code/node_modules/webpack-cli/bin/cli.js:232:39)
    at Object.parse (/code/node_modules/yargs/yargs.js:567:18)
    at /code/node_modules/webpack-cli/bin/cli.js:210:8
    at Object.<anonymous> (/code/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/code/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/code/node_modules/@symfony/webpack-encore/bin/encore.js:63:12)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried `addLoader` too (even if `addRule` is only an alias) but I get the same thing.

This seem to be related to these methods independently on the paramater because even with an empty object it fail.

I'm using webpack-encore `0.22.4` version.

**Comment by Lyrkan** [comment]
Hi @Jerome1337,

I just tested your `addRule` with Encore v0.22.4 and didn't encounter any error.
Does the error go away if you remove that call?
Could you give us your whole `webpack.config.js` file?

**Comment by Jerome1337** [comment]
hi @Lyrkan 

My webpack config is 

```js
const Encore = require('@symfony/webpack-encore');

Encore
  .enableSingleRuntimeChunk()
  .setOutputPath('public/build/')
  .setPublicPath('/build')
  .cleanupOutputBeforeBuild()
  .splitEntryChunks()
  .addEntry('app', './assets/js/app.js')
  .addEntry('front', './assets/js/front.js')
  .addEntry('login', './assets/js/login.js')
  .addEntry('admin', './assets/js/admin.js')
  .addEntry('pdf', './assets/js/pdf.js')
  .addEntry('common', './assets/js/common.js')
  .copyFiles([
    {
      from: './node_modules/highlightjs',
      pattern: /(highlight.pack.min.js)$/u,
    },
    {
      from: './assets/js',
      pattern: /(highlight.worker.js)$/u,
    },
    {
      from: './translations',
      pattern: /(front.*.yml)$/u,
    },
  ])
  .addRule({
    parser: {
      amd: false,
    },
  })
  .enableSassLoader()
  .enablePostCssLoader()
  .enableVueLoader()
  .autoProvideVariables({
    '$': 'jquery',
    'jQuery': 'jquery',
    'window.$': 'jquery',
    'window.jQuery': 'jquery',
  })
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction());

// eslint-disable-next-line one-var
const config = Encore.getWebpackConfig();

config.resolve.alias = {
  handlebars: 'handlebars/dist/handlebars.min.js',
  vue: 'vue/dist/vue.js',
};

if (Encore.isProduction()) {
  /*
   * @see https://github.com/vuejs/vue/issues/5063#issuecomment-301238826
   * @see https://stackoverflow.com/a/41627264/4487542
   * Since Vue 2.1.0 vue.js has been hardcoded as dev env and vue.commom.js as prod env
   */
  config.resolve.alias = {
    vue: 'vue/dist/vue.common.js',
  };
}

// @see https://github.com/symfony/webpack-encore/issues/3#issuecomment-434640816
for (const rule of config.module.rules) {
  if (rule.test.toString() === '/\\.s[ac]ss$/') {
    rule.use = ['css-hot-loader'].concat(rule.use);
  }
}

module.exports = config;
```

I just tested again with Encore `0.22.4` and had the same error
I even tested with Encore `0.23.0` and got the same problem.

**Comment by Lyrkan** [comment]
@Jerome1337 Your issue comes from this line:

```js
if (rule.test.toString() === '/\\.s[ac]ss$/') {
```

Without your `addRule` call it works since all the default rules that are added by Encore all have a `test` property. But since your custom rule don't have that property, `rule.check` will be equal to `undefined`, and calling `toString()`  on it will fail.

You could probably fix that by checking if `rule.test` is set before the `toString()` call.

**Comment by Jerome1337** [comment]
Ok I found the problem, it is because of my 

```js
for (const rule of config.module.rules) {
  if (rule.test.toString() === '/\\.s[ac]ss$/') {
    rule.use = ['css-hot-loader'].concat(rule.use);
  }
}
```

The rule is working well, I will fix that.

Thanks for your reply
