### ISSUE TITLE
Notifier shows warning instead of success

### ISSUE THREAD

**Issue by renedekat** [symfony/webpack-encore#588]
When compiling I get a lovely "WARNING  Compiled with 0 warnings" message instead of an even more beautiful ` DONE  Compiled successfully in 27ms` message.

Is there a way to hide the warnings if there are none and always show the DONE message instead? 

While watching it only shows the DONE message once, but not on subsequent compiles.

<img width="319" alt="Screenshot 2019-06-07 at 15 53 47" src="https://user-images.githubusercontent.com/8975204/59113374-c81e9000-893c-11e9-936e-7d2da12a7e54.png">

<img width="282" alt="Screenshot 2019-06-07 at 15 56 52" src="https://user-images.githubusercontent.com/8975204/59113440-e4bac800-893c-11e9-9959-577be6f31ca3.png">

**Comment by renedekat** [comment]
Found the issue

`(6297:5) Unable to find uri in 'background: url() center center/cover no-repeat transparent'
    at Object.emitWarning (/Users/rene.dekat/Sites/www.redbreastwhiskey.com/node_modules/webpack/lib/NormalModule.js:158:6)
    at result.warnings.forEach.warning (/Users/rene.dekat/Sites/www.redbreastwhiskey.com/node_modules/css-loader/dist/index.js:132:47)
    at Array.forEach (<anonymous>)
    at process.then.result (/Users/rene.dekat/Sites/www.redbreastwhiskey.com/node_modules/css-loader/dist/index.js:132:23)
 WARNING  Compiled with 0 warnings`
