### ISSUE TITLE
Error: Cannot find module '../lib/config/parse-runtime'

### ISSUE THREAD

**Issue by michalpuchmertl** [symfony/webpack-encore#802]
Can you please give me a hand? I tried to run dev server and suddenly this happened.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev-server-ast'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [ 'predev-server-ast', 'dev-server-ast', 'postdev-server-ast' ]
5 info lifecycle @~predev-server-ast: @
6 info lifecycle @~dev-server-ast: @
7 verbose lifecycle @~dev-server-ast: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev-server-ast: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Public/ast2.test/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Volumes/Public/ast2.test/node_modules/.bin
9 verbose lifecycle @~dev-server-ast: CWD: /Volumes/Public/ast2.test
10 silly lifecycle @~dev-server-ast: Args: [ '-c', 'NODE_ENV=ast encore dev-server --host 127.0.0.1 --port 8686' ]
11 silly lifecycle @~dev-server-ast: Returned: code: 1  signal: null
12 info lifecycle @~dev-server-ast: Failed to exec dev-server-ast script
13 verbose stack Error: @ dev-server-ast: `NODE_ENV=ast encore dev-server --host 127.0.0.1 --port 8686`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /Volumes/Public/ast2.test
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev-server-ast"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev-server-ast: `NODE_ENV=ast encore dev-server --host 127.0.0.1 --port 8686`
22 error Exit status 1
23 error Failed at the @ dev-server-ast script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Thanks for any advice.

**Comment by Kocal** [comment]
How did you solve your issue?

**Comment by fri0z** [comment]
It helped me: `npm ci`
