### ISSUE TITLE
HookWebpackError: Problem deleting JS entry for _tmp_copy: 0 files were deleted ()

### ISSUE THREAD

**Issue by indapublic** [symfony/webpack-encore#933]
I see the error "Problem deleting JS entry for _tmp_copy" when trying to copy files using `copyFiles`

Duplicate of #925 but it was resolved with `configureFontRule`, it's not my case.

```
symfony/webpack-encore-bundle        v1.11.0
```

```
@symfony/webpack-encore@1.1.0
```

**webpack.config.js**

```
const Encore = require("@symfony/webpack-encore");

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It"s useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || "dev");
}

Encore
    // directory where compiled assets will be stored
    .setOutputPath("public/build/")
    // public path used by the web server to access the output path
    .setPublicPath("/build")
    // only needed for CDN"s or sub-directory deploy
    //.setManifestKeyPrefix("build/")

    .copyFiles({
        from: "./assets/images",
    })

    /*
     * ENTRY CONFIG
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if your JavaScript imports CSS.
     */
    .addEntry("admin", "./assets/js/admin/app.js")

    .addEntry("app", "./assets/js/app.js")
    .addEntry("product", "./assets/js/product.js")

    // enables the Symfony UX Stimulus bridge (used in assets/bootstrap.js)
    // .enableStimulusBridge("./assets/controllers.json")

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()

    // will require an extra script tag for runtime.js
    // but, you probably want this, unless you"re building a single-page app
    .enableSingleRuntimeChunk()

    /*
     * FEATURE CONFIG
     *
     * Enable & configure other features below. For a full
     * list of features, see:
     * https://symfony.com/doc/current/frontend.html#adding-more-features
     */
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    .configureBabel((config) => {
        config.plugins.push("@babel/plugin-proposal-class-properties");
    })

    // enables @babel/preset-env polyfills
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = "usage";
        config.corejs = 3;
    })

    // enables Sass/SCSS support
    .enableSassLoader()

    // uncomment if you use TypeScript
    //.enableTypeScriptLoader()

    // uncomment if you use React
    .enableReactPreset()

    // uncomment to get integrity="..." attributes on your script & link tags
    // requires WebpackEncoreBundle 1.4 or higher
    //.enableIntegrityHashes(Encore.isProduction())

    // uncomment if you"re having problems with a jQuery plugin
    .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();
```

**Log:**

```
> encore production --progress

Running webpack ...

[webpack-cli] HookWebpackError: Problem deleting JS entry for _tmp_copy: 0 files were deleted ()
    at makeWebpackError (/var/www/app/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at hooks.processAssets.callAsync.err (/var/www/app/node_modules/webpack/lib/Compilation.js:2382:12)
    at eval (eval at create (/var/www/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:81:1)
    at fn (/var/www/app/node_modules/webpack/lib/Compilation.js:373:17)
    at Hook.eval [as callAsync] (eval at create (/var/www/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/app/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/var/www/app/node_modules/webpack/lib/Compilation.js:2379:34)
    at createChunkAssets.err (/var/www/app/node_modules/webpack/lib/Compilation.js:2425:10)
    at /var/www/app/node_modules/neo-async/async.js:2830:7
    at Object.each (/var/www/app/node_modules/neo-async/async.js:2850:39)
-- inner error --
Error: Problem deleting JS entry for _tmp_copy: 0 files were deleted ()
    at compilation.chunks.forEach (/var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:49:27)
    at Set.forEach (<anonymous>)
    at deleteEntries (/var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:18:28)
    at /var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:59:17
    at processAssetsHook.tap (/var/www/app/node_modules/webpack/lib/Compilation.js:474:56)
    at fn (/var/www/app/node_modules/webpack/lib/Compilation.js:371:10)
    at Hook.eval [as callAsync] (eval at create (/var/www/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/app/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/var/www/app/node_modules/webpack/lib/Compilation.js:2379:34)
    at createChunkAssets.err (/var/www/app/node_modules/webpack/lib/Compilation.js:2425:10)
caused by plugins in Compilation.hooks.processAssets
Error: Problem deleting JS entry for _tmp_copy: 0 files were deleted ()
    at compilation.chunks.forEach (/var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:49:27)
    at Set.forEach (<anonymous>)
    at deleteEntries (/var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:18:28)
    at /var/www/app/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:59:17
    at processAssetsHook.tap (/var/www/app/node_modules/webpack/lib/Compilation.js:474:56)
    at fn (/var/www/app/node_modules/webpack/lib/Compilation.js:371:10)
    at Hook.eval [as callAsync] (eval at create (/var/www/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/app/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/var/www/app/node_modules/webpack/lib/Compilation.js:2379:34)
    at createChunkAssets.err (/var/www/app/node_modules/webpack/lib/Compilation.js:2425:10)
```

**Comment by stof** [comment]
which version of encore are you using ?

**Comment by indapublic** [comment]
@stof 

```@symfony/webpack-encore@1.1.0```

**Comment by stof** [comment]
Maybe related to https://github.com/symfony/webpack-encore/issues/894 which has a PR at https://github.com/symfony/webpack-encore/pull/930

**Comment by weaverryan** [comment]
Can you try version 1.1.1? PR #930 fixed some things in that area - so it may have resolved it.

Thanks!

**Comment by indapublic** [comment]
Seems it working now. Thanks @Lyrkan @weaverryan @stof
