### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by giantthinker** [symfony/webpack-encore#961]
Hello devs, this is what I keep getting when this error 
```
PS D:\projects\jobs> yarn watch
yarn run v1.22.10
$ encore dev --watch
Running webpack ...

D:\projects\jobs\node_modules\webpack\lib\NormalModule.js:180
                        throw new TypeError(
                        ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (D:\projects\jobs\node_modules\webpack\lib\NormalModule.js:180:10)
    at D:\projects\jobs\node_modules\@symfony\webpack-encore\lib\webpack-manifest-plugin\index.js:56:24
    at _next28 (eval at create (D:\Projects\jobs\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:50:1)
    at _next6 (eval at create (D:\Projects\jobs\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (D:\Projects\jobs\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:113:1)
    at Hook.CALL_DELEGATE [as _call] (D:\Projects\jobs\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (D:\Projects\jobs\node_modules\webpack\lib\Compiler.js:1015:26)
    at D:\Projects\jobs\node_modules\webpack\lib\Compiler.js:1057:29
    at Hook.eval [as callAsync] (eval at create (D:\Projects\jobs\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Projects\jobs\node_modules\tapable\lib\Hook.js:18:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What could be the problem. Few days ago, it was working fine but now I don't know what's happening.

and this is my webpack 

```js
const Encore = require('@symfony/webpack-encore');

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    // directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // public path used by the web server to access the output path
    .setPublicPath('/build')
    // only needed for CDN's or sub-directory deploy
    .setManifestKeyPrefix('build/')

    //.copyFiles({from: './assets/images'})

    /*
     * ENTRY CONFIG
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if your JavaScript imports CSS.
     */
    .addEntry('app', './assets/app.js')

    // enables the Symfony UX Stimulus bridge (used in assets/bootstrap.js)
    .enableStimulusBridge('./assets/controllers.json')

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()

    // will require an extra script tag for runtime.js
    // but, you probably want this, unless you're building a single-page app
    .enableSingleRuntimeChunk()

    /*
     * FEATURE CONFIG
     *
     * Enable & configure other features below. For a full
     * list of features, see:
     * https://symfony.com/doc/current/frontend.html#adding-more-features
     */
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    .configureBabel((config) => {
        config.plugins.push('@babel/plugin-proposal-class-properties');
    })

    // enables @babel/preset-env polyfills
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })

    // enables Sass/SCSS support
    //.enableSassLoader()

    // uncomment if you use TypeScript
    //.enableTypeScriptLoader()

    // uncomment if you use React
    //.enableReactPreset()

    // uncomment to get integrity="..." attributes on your script & link tags
    // requires WebpackEncoreBundle 1.4 or higher
    //.enableIntegrityHashes(Encore.isProduction())

    // uncomment if you're having problems with a jQuery plugin
    .autoProvidejQuery()
    .addLoader({
        test: require.resolve('jquery'),
        loader: 'expose-loader',
        options: {
            exposes: ['$', 'jQuery', 'tippy'],
        }
    })
;
module.exports = Encore.getWebpackConfig();
```

**Comment by giantthinker** [comment]
After hours of digging, I finally find out that it compiles with Windows CMD and not PowerShell nor Git Bash.

**Comment by alexander-akait** [comment]
Update `mini-css-extract-plugin` to the latest stable version

**Comment by giantthinker** [comment]
Hello @alexander-akait, I don't have `mini-css-extract-plugin` installed and even installing it did not solve the issue.
