### ISSUE TITLE
Upgrade from 1.1.2 to 1.2.0

### ISSUE THREAD

**Issue by kl3sk** [symfony/webpack-encore#972]
When Upgrading to `1.2.0` this error occurs. Any advice ?

```js
9% setup compilation DefinePlugin/home/<user>/<project>/node_modules/@symfony/webpack-encore/node_modules/webpack/lib/util/MapHelpers.js:17
        const value = map.get(key);
                          ^

TypeError: Cannot read property 'get' of undefined
    at exports.provide (/home/<user>/<project>/node_modules/@symfony/webpack-encore/node_modules/webpack/lib/util/MapHelpers.js:17:20)
    at /home/<user>/<project>/node_modules/@symfony/webpack-encore/node_modules/webpack/lib/DefinePlugin.js:289:51
    at Hook.eval [as call] (eval at create (/home/<user>/<project>/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:392:1)
    at Hook.CALL_DELEGATE [as _call] (/home/<user>/<project>/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/<user>/<project>/node_modules/webpack/lib/Compiler.js:993:26)
    at /home/<user>/<project>/node_modules/webpack/lib/Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (/home/<user>/<project>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/<user>/<project>/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/<user>/<project>/node_modules/webpack/lib/Compiler.js:1030:28)
    at /home/<user>/<project>/node_modules/webpack/lib/Watching.js:132:19
```

**Comment by weaverryan** [comment]
Hmm yea, I'm not sure about that - nothing changed in this area. It's more likely (but still a guess) that when you upgraded Encore, you also upgraded Webpack itself - and that caused some issue.

**Comment by kl3sk** [comment]
Thanks you for your answer. But noting related about webpack (unless Encore) was upgraded. 

Webpack is a Encore dependency isn't it ?

**Comment by weaverryan** [comment]
> Webpack is a Encore dependency isn't it ?

Yup! But it's still possible that when you upgraded Encore, the Webpack version was upgraded. 

Here is the diff between the versions in question - https://github.com/symfony/webpack-encore/compare/v1.1.2..v1.2.0 - it is fairly minor in Encore. The biggest thing is that we bumped the Webpack min version from 5.12 to 5.35. My guess is that Webpack upgraded... and you may have a plugin (or something) that is not playing nicely with that new version for some reason. 

Do you use `configureDefinePlugin()`? That is the only time that Encore uses the DefinePlugin directly (that plugin is in the stacktrace).

Cheers!

**Comment by kl3sk** [comment]
Ok I understand your answer now. 

In fact I use `@ckeditor-dev-webpack-plugin` and it look like it's looking for `webpack 5.24.0` and it's certainly the cause. I'll dig on it. 


I close for now and may reopen if needed. 


Thanks again.
