### ISSUE TITLE
"SyncWaterfallHook is not a constructor" when dependencies are installed with yarn

### ISSUE THREAD

**Issue by texmex44** [symfony/webpack-encore#988]
Version concerned : 1.x (no error on 0.33.0)
Command concerned : `yarn run encore -- production`

No errors when dependencies are installed with npm `npm install`
The errors occurs ONLY when i install dependencies with `yarn install`

Stacktrace 
```
HookWebpackError: SyncWaterfallHook is not a constructor
    at makeWebpackError (/var/www/html/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /var/www/html/node_modules/webpack/lib/Compilation.js:2495:12
    at eval (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fn (/var/www/html/node_modules/webpack/lib/Compilation.js:427:17)
    at _next7 (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at eval (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

TypeError: SyncWaterfallHook is not a constructor
    at getCompilerHooks (/var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/hooks.js:17:18)
    at WebpackManifestPlugin.emit (/var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/hooks.js:101:14)
    at /var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/index.js:64:64
    at fn (/var/www/html/node_modules/webpack/lib/Compilation.js:425:10)
    at _next7 (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at eval (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by plugins in Compilation.hooks.processAssets

TypeError: SyncWaterfallHook is not a constructor
    at getCompilerHooks (/var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/hooks.js:17:18)
    at WebpackManifestPlugin.emit (/var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/hooks.js:101:14)
    at /var/www/html/node_modules/@symfony/webpack-encore/lib/webpack-manifest-plugin/index.js:64:64
    at fn (/var/www/html/node_modules/webpack/lib/Compilation.js:425:10)
    at _next7 (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at eval (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by stof** [comment]
Can you run `yarn why tapable` and paste the full output here please ?

**Comment by texmex44** [comment]
@stof Here is the result of `yarn why tapable`

```

yarn why v1.22.10
[1/4] Why do we have the module "tapable"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "tapable@1.1.3"
info Has been hoisted to "tapable"
info Reasons this module exists
   - Hoisted from "enhanced-resolve#tapable"
   - Hoisted from "@symfony#webpack-encore#webpack-manifest-plugin#tapable"
   - Hoisted from "@symfony#webpack-encore#webpack#tapable"
info Disk size without dependencies: "100KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 0
=> Found "purgecss-webpack-plugin#tapable@2.2.0"
info Reasons this module exists
   - "purgecss-webpack-plugin#webpack" depends on it
   - Hoisted from "purgecss-webpack-plugin#webpack#tapable"
   - Hoisted from "purgecss-webpack-plugin#webpack#enhanced-resolve#tapable"
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "104KB"
info Disk size with transitive dependencies: "104KB"
info Number of shared dependencies: 0
=> Found "webpack#tapable@0.1.10"
info Reasons this module exists
   - "react-numeral#webpack" depends on it
   - Hoisted from "react-numeral#webpack#enhanced-resolve#tapable"
Done in 1.08s.

```

**Comment by stof** [comment]
Can you also run `yarn why webpack` ? The previous output makes me think that you might have multiple versions of webpack installed (maybe due to some plugins being for a different version of webpack)

**Comment by texmex44** [comment]
It seems you have right, but how to fix this ?
```
yarn why v1.22.10
[1/4] Why do we have the module "webpack"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "webpack@1.15.0"
info Reasons this module exists
   - "react-numeral" depends on it
   - Hoisted from "react-numeral#webpack"
info Disk size without dependencies: "3.14MB"
info Disk size with unique dependencies: "8.2MB"
info Disk size with transitive dependencies: "18.95MB"
info Number of shared dependencies: 128
=> Found "@symfony/webpack-encore#webpack@4.46.0"
info This module exists because "@symfony#webpack-encore" depends on it.
=> Found "purgecss-webpack-plugin#webpack@5.37.1"
info This module exists because "purgecss-webpack-plugin" depends on it.
info Disk size without dependencies: "5.39MB"
info Disk size with unique dependencies: "10.64MB"
info Disk size with transitive dependencies: "30.99MB"
info Number of shared dependencies: 133
Done in 4.36s.

```

**Comment by stof** [comment]
Either downgrade the `purgecss-webpack-plugin` and `react-numeral` plugins to versions using webpack 4, or upgrade `@symfony/webpack-encore` to 1.0 so that it uses wbepack 5.

**Comment by texmex44** [comment]
ok my bad that's because i run my command on the bad server.  So on the server i have try to update `@symfony/webpack-encore` and who trig the error i have :

```
=> Found "webpack@5.37.1"
info Has been hoisted to "webpack"
info Reasons this module exists
   - Hoisted from "@symfony#webpack-encore#webpack"
   - Hoisted from "purgecss-webpack-plugin#webpack"
info Disk size without dependencies: "5.5MB"
info Disk size with unique dependencies: "8.73MB"
info Disk size with transitive dependencies: "22.06MB"
info Number of shared dependencies: 42
=> Found "react-numeral#webpack@1.15.0"
info This module exists because "react-numeral" depends on it.
info Disk size without dependencies: "1.16MB"
info Disk size with unique dependencies: "5.48MB"
info Disk size with transitive dependencies: "15.14MB"
info Number of shared dependencies: 61
Done in 0.90s.
```

So the problem come from `react-numeral`?

**Comment by stof** [comment]
Well, `react-numeral` using webpack 1 will indeed break things.

Looking at the `react-numeral` package, its github repo has a single commit done in 2017. I would not call that a maintained package.

**Comment by texmex44** [comment]
Understood, but can you say me why i have no errors on build when package are installed with a classic `npm install` ?

**Comment by stof** [comment]
probably because of a different hoisting performed by npm vs yarn.

**Comment by soullivaneuh** [comment]
Had the issue with yarn, found only two solution:

1. Use npm to manage your modules.
2. Run `yarn add webpack`, the package will be dedupe.

Still looks like dirty workaround to me, but this is what I found so far.

**Comment by kaizokou** [comment]
I had this issue also with opensea-js
As stof said I had to downgrade @symfony/webpack-encore 
I used https://yarnpkg.com/package/@symfony/webpack-encore to find and try the different versions until I found one that worked
To downgrade just edit the 'symfony/webpack-encore ' version number in your package.json under the devDependencies key
